/edep/phys/ionizationModel 0
/edep/gdml/read /Users/yuntse/work/lartpc_rd/GAMPix4SNe/MCProd/g4/gdml/InfiniteLAr.gdml

/edep/db/set/neutronThreshold 0 MeV
/edep/db/set/lengthThreshold 0 mm
/edep/db/set/gammaThreshold 0 MeV
/edep/db/open /Users/yuntse/data/lartpc_rd/gampix/g4/radiologicals/fullgeoanatruth-vd-reduced_g4_00_model0.root
# /edep/db/set/storeROOT true

/edep/hitSagitta LArVol 1.0 mm
/edep/hitLength LArVol 1.0 mm
/edep/hitSeparation LArVol -1 mm

/edep/update

/generator/kinematics/set hepevt

/generator/kinematics/hepevt/input /Users/yuntse/data/lartpc_rd/gampix/gen/radiologicals/fullgeoanatruth-vd-reduced_00.hepevt
/generator/kinematics/hepevt/flavor marley

/generator/count/set hepevt
/generator/count/hepevt/input /Users/yuntse/data/lartpc_rd/gampix/gen/radiologicals/fullgeoanatruth-vd-reduced_00.hepevt

## Distribute the events based on the vertex in the rooTracker file.
/generator/position/set free

## Distribute the event times based onn the time in the rooTracker file.
/generator/time/set free

## Make sure EDEPSIM updates the kinematics generator.
/generator/add

# /run/beamOn 1000
/run/beamOn 1
